title: CrocPRM Patch Notes
description: Atualizações e downloads do servidor
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# (opcional) ajuste conforme seu repositório:
# url: "https://SEUUSER.github.io"
# baseurl: "/NOMEDOREPO"   # deixe vazio se for site de usuário
timezone: America/Sao_Paulo
markdown: kramdown
kramdown:
  input: GFM
