title: CrocPRM Server
description: Revivendo o PRM até o magnânimo Luna Obscura!

# Configuração para GitHub Pages
url: "https://concs93.github.io"
baseurl: "/CrocPRMsite"

timezone: America/Sao_Paulo
markdown: kramdown
kramdown:
  input: GFM

# Configurações de layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
